### ISSUE TITLE
Record Video and Audio

### ISSUE THREAD

**Issue by LoganArnett** [shavit/Monique#1]
Hello @shavit 

First of all this project is awesome, I have been messing around with it for a few days now. 

I was wondering if you have any insight on how to get audio into the videos that are being recorded? I am trying to record from the webcam and record audio from an external microphone. 

Any help or insight would be greatly appreciated

**Comment by shavit** [comment]
See https://github.com/shavit/Monique/commit/60c673f36ebcf59bd51589036e2ffbf2e7060b11, I should update the asset writer to include audio, but the mp4 files should have audio.

**Comment by LoganArnett** [comment]
Awesome, thank you for pointing that out. I have updated to the Swift 4 version and the sound is coming in.

**Comment by LoganArnett** [comment]
So I have been messing around with that new branch and it is working great. My only question is do you know why a video of under 10 seconds can have both audio and video but after 10 seconds the sound will no longer be included?

**Comment by LoganArnett** [comment]
Found [this](https://developer.apple.com/documentation/avfoundation/avcapturemoviefileoutput/1387146-moviefragmentinterval) today and was able to make it work, looks like a bug in the `AVCaptureSession`

**Comment by shavit** [comment]
Thanks, I will take a look
